# Know default icon in EditorStyle set
EditorStyle = [
    "Kismet.Status.Unknown"
    "Kismet.Status.Error"
    "Kismet.Status.Good"
    "Kismet.Status.Warning"

    "AssetEditor.SaveAsset"
    "SystemWideCommands.FindInContentBrowser"
    "BlueprintEditor.FindInBlueprint"
    "MaterialEditor.FindInMaterial"
    "TranslationEditor.Search"

    "FullBlueprintEditor.EditGlobalOptions"
    "FullBlueprintEditor.EditClassDefaults"
    "FullBlueprintEditor.SwitchToBlueprintDefaultsMode"
    "BlueprintEditor.EnableSimulation"
    "PlayWorld.PlayInViewport"
    "GraphEditor.ToggleHideUnrelatedNodes"
    "LevelEditor.Build"
    "LevelEditor.Recompile"
    "LevelEditor.OpenContentBrowser"
    "LevelEditor.EditorModes"
    "LevelEditor.ToggleVR"
    "LevelEditor.GameSettings"
    "LevelEditor.OpenLevelBlueprint"
    "LevelEditor.OpenMarketplace"
    "LevelEditor.EditMatinee"

    "LevelEditor.SourceControl"
    "LevelEditor.SourceControl.On"
    "LevelEditor.SourceControl.Off"
    "LevelEditor.SourceControl.Unknown"
    "LevelEditor.SourceControl.Problem"
    "MaterialEditor.Apply"
    "MaterialEditor.CameraHome"
    "MaterialEditor.ToggleRealtimeExpressions"
    "MaterialEditor.AlwaysRefreshAllPreviews"
    "MaterialEditor.ToggleLivePreview"
    "MaterialEditor.ToggleMaterialStats"
    "MaterialEditor.TogglePlatformStats"
    "MaterialEditor.CleanUnusedExpressions"
    "MaterialEditor.ShowHideConnectors"

    "PlayWorld.PausePlaySession"
    "PlayWorld.StopPlaySession"
    "PlayWorld.PossessPlayer"
    "PlayWorld.EjectFromPlayer"
    "PlayWorld.RepeatLastLaunch"
    "PlayWorld.PlayInNewProcess"
    "PlayWorld.PlayInEditorFloating"
    "PlayWorld.PlayInMobilePreview"
    "PlayWorld.PlayInVR"
    "PlayWorld.LateJoinSession"
    "PlayWorld.ResumePlaySession"
    "PlayWorld.Simulate"
    "PlayWorld.RepeatLastPlay"

    "PlayWorld.SingleFrameAdvance"
    "PlayWorld.ShowCurrentStatement"
    "PlayWorld.StepOut"
    "PlayWorld.StepInto"
    "PlayWorld.StepOver"

    "BTEditor.SwitchToBehaviorTreeMode"
    "UMGEditor.SwitchToDesigner"
    "FullBlueprintEditor.SwitchToScriptingMode"

    "EditorViewport.ToggleRealTime"

    "StaticMeshEditor.SetShowWireframe"
    "StaticMeshEditor.SetShowVertexColor"
    "StaticMeshEditor.SetRealtimePreview"
    "StaticMeshEditor.ReimportMesh"
    "StaticMeshEditor.SetShowBounds"
    "StaticMeshEditor.SetShowCollision"
    "StaticMeshEditor.SetShowGrid"
    "StaticMeshEditor.SetDrawUVs"
    "StaticMeshEditor.ResetCamera"
    "StaticMeshEditor.SetShowPivot"
    "StaticMeshEditor.SetShowSockets"
    "StaticMeshEditor.SetShowNormals"
    "StaticMeshEditor.SetShowTangents"
    "StaticMeshEditor.SetShowBinormals"
    "StaticMeshEditor.SetDrawAdditionalData"
    "StaticMeshEditor.SetShowVertices"
    "StaticMeshEditor.ToggleShowPivots"
    "StaticMeshEditor.ToggleShowSockets"
    "StaticMeshEditor.ToggleShowNormals"
    "StaticMeshEditor.ToggleShowTangents"
    "StaticMeshEditor.ToggleShowBinormals"
    "StaticMeshEditor.ToggleShowBounds"
    "StaticMeshEditor.ToggleShowGrids"
    "StaticMeshEditor.ToggleShowVertices"
    "StaticMeshEditor.ToggleShowWireframes"
    "StaticMeshEditor.ToggleShowVertexColors"
    "Persona.BakeMaterials"

    "AnimationEditor.ApplyCompression"
    "AnimationEditor.ExportToFBX"
    "AnimationEditor.ReimportAnimation"
    "AnimationEditor.CreateAsset"
    "AnimationEditor.SetKey"
    "AnimationEditor.ApplyAnimation"

    "Persona.TogglePreviewAsset"
    "Persona.CreateAsset"
    "Persona.ExportToFBX"
    "Persona.ConvertToStaticMesh"

    "EditorViewport.LocationGridSnap"
    "EditorViewport.RotationGridSnap"
    "EditorViewport.Layer2DSnap"
    "EditorViewport.ScaleGridSnap"
    "EditorViewport.ToggleSurfaceSnapping"
    "EditorViewport.RelativeCoordinateSystem_Local"
    "EditorViewport.RelativeCoordinateSystem_Local.Small"
    "EditorViewport.RelativeCoordinateSystem_World"
    "EditorViewport.RelativeCoordinateSystem_World.Small"
    "EditorViewport.CamSpeedSetting"

    "DetailsView.EditRawProperties"

    "CurveEd.Visible"
    "CurveEd.VisibleHighlight"
    "CurveEd.Invisible"
    "CurveEd.InvisibleHighlight"
    "Level.VisibleIcon16x"
    "Level.VisibleHighlightIcon16x"
    "Level.NotVisibleIcon16x"
    "Level.NotVisibleHighlightIcon16x"
    "GenericViewButton"

    "PropertyWindow.Button_CreateNewBlueprint"
    "PropertyWindow.Button_Browse"
    "PropertyWindow.Button_Use"

    "GenericLock"
    "GenericLock.Small"
    "GenericUnlock"
    "GenericUnlock.Small"
    "PropertyWindow.Locked"
    "PropertyWindow.Unlocked"
    "FindResults.LockButton_Locked"
    "FindResults.LockButton_Unlocked"
    "ContentBrowser.LockButton_Locked"
    "ContentBrowser.LockButton_Unlocked"

    "DetailsView.PulldownArrow.Down"
    "DetailsView.PulldownArrow.Down.Hovered"
    "DetailsView.PulldownArrow.Up"
    "DetailsView.PulldownArrow.Up.Hovered"

    "TreeArrow_Collapsed"
    "TreeArrow_Collapsed_Hovered"
    "TreeArrow_Expanded"
    "TreeArrow_Expanded_Hovered"

    "EditorViewport.TranslateMode"
    "EditorViewport.RotateMode"
    "EditorViewport.ScaleMode"

    "TimelineEditor.AddFloatTrack"
    "TimelineEditor.AddVectorTrack"
    "TimelineEditor.AddEventTrack"
    "TimelineEditor.AddColorTrack"
    "TimelineEditor.AddCurveAssetTrack"
    "TimelineEditor.DeleteTrack"
]